### ISSUE TITLE
Missing $notifiable parameter

### ISSUE THREAD

**Issue by nurmanhabib** [tkaratug/laravel-notification-event-subscriber#2]
Looks like you forgot the notifiable variable in `onSending` and `onSent` methods needs to add the `$notifiable` parameter to know to whom the notification is running.

**Comment by tkaratug** [comment]
Fixed with [pr#3](https://github.com/tkaratug/laravel-notification-event-subscriber/pull/3). Thanks for the contribution @nurmanhabib.
